apiVersion: batch/v1
kind: Job
metadata:
  name: copy-wildcard-secret-to-kong
  namespace: cert-manager
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/sync-wave": "1"
spec:
  template:
    spec:
      containers:
        - name: copy-secret
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              kubectl get secret bizquery-wildcard-tls -n cert-manager -o yaml \
              | sed 's/namespace: cert-manager/namespace: kong/' \
              | kubectl apply -f -
      restartPolicy: Never
