apiVersion: batch/v1
kind: Job
metadata:
  name: patch-wildcard-secret
  namespace: cert-manager
  annotations:
    "argocd.argoproj.io/hook": PostSync
spec:
  template:
    spec:
      containers:
        - name: patcher
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              kubectl annotate secret bizquery-wildcard-tls \
                -n cert-manager \
                kubed.appscode.com/sync="kong,argocd" --overwrite
      restartPolicy: Never
