provider "digitalocean" {
  token = var.do_token
}

resource "digitalocean_project" "main" {
  name        = var.project_name
  description = "BizQuery ${var.env} infrastructure"
  purpose     = "Web Application Hosting"
  environment = {
    dev     = "Development"
    staging = "Staging"
    prod    = "Production"
  }[var.env]
}

resource "digitalocean_domain" "this" {
  name = var.domain_name
}

# module "cluster" is generated by Terragrunt (literal module source path; see environments/dev/doks).

resource "digitalocean_project_resources" "default" {
  project = digitalocean_project.main.id
  resources = [
    module.cluster.cluster_urn,
    digitalocean_domain.this.urn
  ]
}
