provider "digitalocean" {
  token = var.do_token
}

data "digitalocean_project" "existing" {
  name = var.project_name
}

data "digitalocean_domain" "existing" {
  name = var.domain_name
}

# module "cluster" is generated by Terragrunt (literal module source path; see environments/dev/doks).

resource "digitalocean_project_resources" "default" {
  project = data.digitalocean_project.existing.id
  resources = [
    module.cluster.cluster_urn,
    data.digitalocean_domain.existing.urn
  ]
}
