provider "digitalocean" {
  token = var.do_token
}

locals {
  # DO only allows Development | Staging | Production
  project_environment = contains(["prod", "production"], lower(var.env)) ? "Production" : (
    lower(var.env) == "staging" ? "Staging" : "Development"
  )
}

# Managed project so destroy removes it (data source only looked up an existing project).
resource "digitalocean_project" "main" {
  name        = var.project_name
  description = "Managed by Terraform (${var.env})"
  purpose     = "Web Application"
  environment = local.project_environment
}

data "digitalocean_domain" "existing" {
  name = var.domain_name
}

# module "cluster" is generated by Terragrunt (literal module source path; see environments/dev/doks).
# depends_on [digitalocean_project.main] ensures destroy order: cluster first, then project.

resource "digitalocean_project_resources" "default" {
  project = digitalocean_project.main.id
  resources = [
    module.cluster.cluster_urn,
    data.digitalocean_domain.existing.urn
  ]
}
