apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loading-page-ingress
  namespace: loading-page
spec:
  ingressClassName: kong
  rules:
    - host: bizquery.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loading-page-service
                port:
                  number: 80
  tls:
    - hosts:
        - bizquery.dev
      secretName: bizquery-wildcard-tls
