apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bizquery-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: loading-page
            path: k8s/apps/dev/loading-page
            namespace: loading-page
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/jyojith/do-terraform.git
        targetRevision: main
        path: '{{path}}'
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
