provider "digitalocean" {
  token = var.do_token
}

# module "database" is generated by Terragrunt (literal module source path; see
# environments/dev/database/terragrunt.hcl).

# The doks stack OWNS (creates) the DO Project; this stack only looks it up by name and adds the
# database cluster to it — without this, the cluster lands in DO's default/uncategorized project.
data "digitalocean_project" "existing" {
  name = var.project_name
}

resource "digitalocean_project_resources" "database" {
  project   = data.digitalocean_project.existing.id
  resources = [module.database.urn]
}
